//! Homing / zero-length calibration helpers.

use serde::{Deserialize, Serialize};
use spyder_core::{Pose, Robot, Vec3};

use crate::{Result, RuntimeError};

/// Measured / configured calibration snapshot.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Calibration {
    /// World pose considered "home" (meters).
    pub home: [f64; 3],
    /// Ideal IK cable lengths at home (meters) — geometric zero reference.
    pub home_lengths_m: Vec<f64>,
    /// Winch drum radius used for step mapping (meters).
    pub drum_radius_m: f64,
    /// Motor steps per winch revolution (after gearing).
    pub steps_per_rev: f64,
    /// Optional measured anchor exits overriding the robot preset.
    pub anchors_m: Option<Vec<[f64; 3]>>,
    /// ISO-ish timestamp string (informational).
    pub saved_at: String,
}

impl Calibration {
    /// Capture calibration from a robot at `home` with actuation params.
    pub fn capture(
        robot: &Robot,
        home: Vec3,
        drum_radius_m: f64,
        steps_per_rev: f64,
    ) -> Result<Self> {
        if drum_radius_m <= 0.0 || steps_per_rev <= 0.0 {
            return Err(RuntimeError::Config(
                "drum_radius and steps_per_rev must be > 0".into(),
            ));
        }
        let ik = robot.ik(&Pose::from_position(home))?;
        let anchors_m = Some(
            robot
                .anchors
                .iter()
                .map(|a| [a.exit.x, a.exit.y, a.exit.z])
                .collect(),
        );
        Ok(Self {
            home: [home.x, home.y, home.z],
            home_lengths_m: ik.lengths,
            drum_radius_m,
            steps_per_rev,
            anchors_m,
            saved_at: chrono_lite_now(),
        })
    }

    /// Home as Vec3.
    pub fn home_vec(&self) -> Vec3 {
        Vec3::new(self.home[0], self.home[1], self.home[2])
    }

    /// Write JSON calibration file.
    pub fn save_json(&self, path: &std::path::Path) -> Result<()> {
        let text = serde_json::to_string_pretty(self)
            .map_err(|e| RuntimeError::Config(e.to_string()))?;
        std::fs::write(path, text).map_err(|e| RuntimeError::Backend(e.to_string()))
    }

    /// Load JSON calibration file.
    pub fn load_json(path: &std::path::Path) -> Result<Self> {
        let text =
            std::fs::read_to_string(path).map_err(|e| RuntimeError::Backend(e.to_string()))?;
        serde_json::from_str(&text).map_err(|e| RuntimeError::Config(e.to_string()))
    }
}

fn chrono_lite_now() -> String {
    // Avoid chrono dep: use system time since epoch.
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format!("unix:{secs}")
}

/// Apply measured anchors onto a robot (point-mass attachments preserved).
pub fn apply_anchor_override(robot: &mut Robot, anchors_m: &[[f64; 3]]) -> Result<()> {
    if anchors_m.len() != robot.anchors.len() {
        return Err(RuntimeError::Config(
            "anchor override count must match robot".into(),
        ));
    }
    for (dst, src) in robot.anchors.iter_mut().zip(anchors_m.iter()) {
        dst.exit = Vec3::new(src[0], src[1], src[2]);
    }
    Ok(())
}

/// Build a venue TOML string from measured anchors + home (field calibration output).
pub fn venue_toml_from_anchors(
    anchors_m: &[[f64; 3]],
    home: Vec3,
    point_mass: bool,
    attachments: Option<&[[f64; 3]]>,
    drum_radius_m: f64,
    steps_per_rev: f64,
) -> Result<String> {
    if anchors_m.len() < 3 {
        return Err(RuntimeError::Config("need at least 3 anchors".into()));
    }
    if let Some(atts) = attachments {
        if atts.len() != anchors_m.len() {
            return Err(RuntimeError::Config(
                "attachments must match anchor count".into(),
            ));
        }
    }
    let mut out = String::new();
    out.push_str("# Generated by spyder field-cal — measured venue layout\n");
    out.push_str(&format!("point_mass = {}\n", if point_mass { "true" } else { "false" }));
    out.push_str(&format!("drum_radius_m = {drum_radius_m}\n"));
    out.push_str(&format!("steps_per_rev = {steps_per_rev}\n\n"));
    for (i, a) in anchors_m.iter().enumerate() {
        out.push_str("[[anchors]]\n");
        out.push_str(&format!("# cable {i}\n"));
        out.push_str(&format!("x = {}\n", a[0]));
        out.push_str(&format!("y = {}\n", a[1]));
        out.push_str(&format!("z = {}\n\n", a[2]));
    }
    if let Some(atts) = attachments {
        for (i, b) in atts.iter().enumerate() {
            out.push_str("[[attachments]]\n");
            out.push_str(&format!("# body point {i}\n"));
            out.push_str(&format!("x = {}\n", b[0]));
            out.push_str(&format!("y = {}\n", b[1]));
            out.push_str(&format!("z = {}\n\n", b[2]));
        }
    }
    out.push_str("[home]\n");
    out.push_str(&format!("x = {}\n", home.x));
    out.push_str(&format!("y = {}\n", home.y));
    out.push_str(&format!("z = {}\n", home.z));
    Ok(out)
}

impl Calibration {
    /// Emit a venue TOML from this calibration's measured anchors + home.
    pub fn to_venue_toml(&self, point_mass: bool) -> Result<String> {
        let anchors = self.anchors_m.as_ref().ok_or_else(|| {
            RuntimeError::Config("calibration has no anchors_m to write venue".into())
        })?;
        venue_toml_from_anchors(
            anchors,
            self.home_vec(),
            point_mass,
            None,
            self.drum_radius_m,
            self.steps_per_rev,
        )
    }

    /// Write venue TOML to disk.
    pub fn save_venue_toml(&self, path: &std::path::Path, point_mass: bool) -> Result<()> {
        let text = self.to_venue_toml(point_mass)?;
        if let Some(parent) = path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        std::fs::write(path, text).map_err(|e| RuntimeError::Backend(e.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;
    use spyder_core::Preset;
    use std::path::PathBuf;

    #[test]
    fn capture_and_roundtrip_json() {
        let robot = Robot::from_preset(Preset::Rect {
            width: 4.0,
            depth: 4.0,
            height: 3.0,
        })
        .unwrap();
        let home = Vec3::new(0.0, 0.0, 1.2);
        let cal = Calibration::capture(&robot, home, 0.05, 200.0).unwrap();
        assert_eq!(cal.home_lengths_m.len(), 4);
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../target/test-cal");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("cal.json");
        cal.save_json(&path).unwrap();
        let loaded = Calibration::load_json(&path).unwrap();
        assert_eq!(loaded.home_lengths_m, cal.home_lengths_m);
    }

    #[test]
    fn venue_toml_contains_anchors_and_home() {
        let anchors = [
            [5.0, 3.0, 8.0],
            [-5.0, 3.0, 8.0],
            [-5.0, -3.0, 8.0],
            [5.0, -3.0, 8.0],
        ];
        let toml = venue_toml_from_anchors(
            &anchors,
            Vec3::new(0.0, 0.0, 1.5),
            true,
            None,
            0.05,
            200.0,
        )
        .unwrap();
        assert!(toml.contains("[[anchors]]"));
        assert!(toml.contains("x = 5"));
        assert!(toml.contains("[home]"));
        assert!(toml.contains("z = 1.5"));
        assert!(toml.contains("point_mass = true"));
    }

    #[test]
    fn apply_anchor_override_updates_exits() {
        let robot = Robot::from_preset(Preset::Rect {
            width: 4.0,
            depth: 4.0,
            height: 3.0,
        })
        .unwrap();
        let mut r = robot.clone();
        let overrides = [[9.0, 9.0, 9.0]; 4];
        apply_anchor_override(&mut r, &overrides).unwrap();
        assert_relative_eq!(r.anchors[0].exit.x, 9.0);
        let err = apply_anchor_override(&mut r, &[[1.0, 2.0, 3.0]]);
        assert!(err.is_err());
    }
}
